version: '3'

services:
  web:
    build:
      . 
    volumes:
      - ./www:/var/www/html
      - ./conf/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - 22:22
    user: "root:root"
    extra_hosts:
      - "bx.doc:127.0.0.1"
    # dns_search:
    #   - bx.doc
    depends_on:
      - mysql
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker" 
      
  nginx:
    # image: nginx:1.16
    build:
      ./conf/nginx 
    ports:
      - 80:80
    extra_hosts:
      - "bx.doc:127.0.0.1"
    # dns_search:
    #   - bx.doc
    volumes: 
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
    volumes_from:
      - web
 
  mysql:
    build: 
      ./conf/mysql
 #   volumes:
 #     - ./conf/mysql:/var/lib/mysql 
 
 #   command: bash -c "chmod 644 /var/run/mysqld"
    ports:
      - "3306:3306" 
    environment:
      MYSQL_ROOT: 'root'
      MYSQL_ROOT_PASSWORD: 0000
      MYSQL_DATABASE: sitemanager
      MYSQL_USER: bitrix
      MYSQL_PASSWORD: 1234
      UPLOAD_LIMIT: 300M
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_unicode_ci', '--wait_timeout=28800', '--max_allowed_packet=256M', '--sql_mode=ONLY_FULL_GROUP_BY,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION', '--interactive_timeout=28800']
   

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:db
    ports:
      - 8765:80
    restart: always 
    volumes:
     - /var/lib/mysql_data:/var/lib/mysql 
    environment:
      MYSQL_ROOT: 'root'
      MYSQL_ROOT_PASSWORD: 0000
      MYSQL_USER: 'bitrix'
      MYSQL_PASS: '1234'
      UPLOAD_LIMIT: 300M
    depends_on:
      - mysql
      
 
 